### ISSUE TITLE
relativeRoot just prepends the string to the path?

### ISSUE THREAD

**Issue by snoepkast** [OverZealous/gulp-cdnizer#16]
File tree:
```
frontend/
    app/
    vendor/
        some/
            folder/
                my.css
                images/
                    image.png
```

My.css:
```css
.some-class {
    background-image: url('./images/image.png');
}
```

Task:
```javascript
gulp.task('vendor-css', [], function() {
    return gulp.src(config.vendor.css.src)
        .pipe(cdnizer({
            defaultCDNBase: config.cdn.defaultBase,
            files: ['**/*.{gif,png,jpg,jpeg,svg,ico}'],
            relativeRoot: 'frontend/'  // Also tried it with 'vendor/'
        }))
        .pipe(gulp.dest(config.vendor.buildDir))
});
```

Result:
```css
.some-class {
    background-image: url('myCDN/frontend/images/image.png');
}
```

Expected result:
```css
.some-class {
    background-image: url('myCDN/frontend/vendor/some/folder/images/image.png');
}
```

Reading the docs I would expect the path to be absolute after being cdnized, but perhaps the fault lies with me again. See anything wrong with my setup or is this really a bug?
