### ISSUE TITLE
Exclude http and https urls

### ISSUE THREAD

**Issue by nathanredblur** [OverZealous/gulp-cdnizer#21]
Hello, I test this but I have an issue.
this is my css
```css
.class1{
   background-image:url(/something.png);
}

.class2{
   background-image:url(https://maps.gstatic.com/mapfiles/api-3/images/powered-by-google-on-white3_hdpi.png);
}
```

```javascript
gulp.task('cdnizer', function () {
  return gulp.src("./dist/css/*.css")
    .pipe(cdnizer({
        defaultCDNBase: '//cdn.my-host.com/',
        relativeRoot: 'css',
        files: ['**/*.{gif,png,jpg,jpeg}']
    }))
    .pipe(gulp.dest("./dist/css/"));
});
```

I need cdnize my local files, but not my extern image.
How can I do that?

I try thinks like
```javascript
files: ['**/*.{gif,png,jpg,jpeg}', '!https:/**/*.png']
```

but not success.
