### ISSUE TITLE
[QUESTION / ISSUE] How to delete relative path?

### ISSUE THREAD

**Issue by YukoOshima** [OverZealous/gulp-cdnizer#29]
Hello there,
I'm working gulp-cdnizer to change my css files' image url. But I don't know how to remove the relative path.
Here's my example to explain what I want.
```css
/* Before */
a.active{background-image:url(../images/button-active.png)}

/* After */
a.active{background-image:url(//my.cdn.url/button-active.png)}
```

That's what I want, but If I write options in this way.

```javascript
gulp.task('prod:less', function () {
    return gulp.src('./src/less/**/*.less')
        .pipe(less({
            paths: [path.join(__dirname, 'less', 'includes')]
        }))
        .pipe(cleanCss({
            compatibility: 'ie8'
        }))
        .pipe(cdnizer({
            defaultCDNBase: '//my.cdn.url/',
            relativeRoot: 'images/',
            files: ['**/*.{gif,png,jpg,jpeg}']
        }))
    .pipe(gulp.dest('./dist/css'));
});
```

The output css will be looked like this way

```css
a.active{background-image:url(//my.cdn.url/images/button-active.png)}
```

I can't remove relative path.
What should I do?
Thanks.
